### Goal Description

This goal measures how sustainably people harvest non-food products from the sea.
From seashells and sponges to aquarium fish, natural products contribute to local economies and international trade. **For the BHI sprat was included as a natural product** because it often used for fish meal production or animal food.

### Model & Data Overview

The data used for this goal are composed of total sprat spawning biomass (SSB) and fishing mortality (F) data. The current status is calculated as a function of the ratio (B’) between the single species current biomass at sea (B) and the reference biomass at maximum sustainable yield (BMSY), as well as the ratio (F’) between the single species current fishing mortality (F) and the fishing mortality at maximum sustainable yield (FMSY). B/Bmsy and F/Fmsy data are converted to scores between 0 and 1 using this [general relationship](https://github.com/OHI-Science/bhi/blob/draft/baltic2015/prep/FIS/ffms%3By_bbmsy_2_score.png).


- [Sprat data accessed from the ICES homepage](http://www.ices.dk/marine-data/tools/Pages/stock-assessment-graphs.aspx) > search for 'sprat' > specify the ecoregion as Baltic Sea > search for the 2013 assessment. 


### Reference points

The reference point used for the computation are based on the MSY principle and are described as a functional relationship. MSY means the highest theoretical equilibrium yield that can be continuously taken on average from a stock under existing average environmental conditions without significantly affecting the reproduction process *(European Union 2013, World Ocean Review 2013).* 

### Considerations for _BHI 2.0_

### Other information

*External advisors/goalkeepers are Christian Möllmann & Stefan Neuenfeldt*

